package se.lexicon.price.component.test.common.entity;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceRouting;
import com.so4it.annotation.Allowed;
import com.so4it.common.util.object.Required;
import com.so4it.component.entity.AbstractEntityBuilder;
import com.so4it.component.entity.IdEntity;
import se.lexicon.price.component.domain.Money;

@SpaceClass
public class DealEntity extends IdEntity<String> {

    @Allowed(value="Auto generated by GS",types = {Allowed.Type.NULLABLE})
    private String id;

    private String instrument;

    private Boolean closed;

    private Money value;

    private DealEntity(){

    }

    private DealEntity(Builder builder){
        this.id=builder.id;
        this.instrument= Required.notNull(builder.instrument,"instrument",builder.isTemplate());
        this.closed =Required.notNull(builder.closed,"closed",builder.isTemplate());
        this.value = builder.value;
    }


    @Override
    @SpaceId(autoGenerate = true)
    public String getId() {
        return id;
    }

    private void setId(String id){
        this.id =id;
    }

    @SpaceRouting
    public String getInstrument(){
        return instrument;
    }

    private void setInstrument(String instrument){
        this.instrument = instrument;

    }

    public Money getValue() {
        return value;
    }

    public void setValue(Money value) {
        this.value = value;
    }

    public Boolean getClosed() {
        return closed;
    }

    private void setClosed(Boolean closed) {
        this.closed = closed;
    }

    public static Builder builder(){
        return new Builder(false);
    }

    public static Builder templateBuilder(){
        return new Builder(true);
    }

    public static class Builder extends AbstractEntityBuilder<DealEntity> {

        private String id;
        private String instrument;
        private Boolean closed;
        private Money value;

        public Builder(boolean template){
            super(template);
        }

        public DealEntity.Builder withId(String id){
            this.id=id;
            return this;
        }

        public DealEntity.Builder withInstrument(String instrument){
            this.instrument=instrument;
            return this;
        }

        public DealEntity.Builder withClosed(Boolean closed){
            this.closed=closed;
            return this;
        }

        public DealEntity.Builder withValue(Boolean closed){
            this.value=value;
            return this;
        }

        @Override
        public DealEntity build(){
            return new DealEntity(this);
        }
    }
}